### ISSUE TITLE
Apex 5.0.1.00.06

### ISSUE THREAD

**Issue by SmileyMan** [RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex#1]
Hi.

Is there any modification I can make to this for it to be compatible with 5.0.1?

Thanks.

**Comment by RonnyWeiss** [comment]
Hello

Maybe you could try wwv_flow_api.import_begin (
 p_version_yyyy_mm_dd=>'2016.08.24'
,p_release=>'5.1.3.00.05'

to 

wwv_flow_api.import_begin (
 p_version_yyyy_mm_dd=>'2013.01.01'
,p_release=>'5.0.3.00.03'

in sql file. But I can not gurantee that this will work. But you could try

Kind regards

Ronny

**Comment by SmileyMan** [comment]
Execution of the statement was unsuccessful. ORA-06550: line 8, column 16: PLS-00201: identifier 'WWV_FLOW_STRING.JOIN' must be declared ORA-06550: line 2, column 1: PL/SQL: Statement ignored ORA-06550: line 145, column 19: PLS-00201: identifier 'WWV_FLOW_STRING.JOIN' must be declared ORA-06550: line 136, column 1: PL/SQL: Statement ignored ORA-06550: line 172, column 19: PLS-00201: identifier 'WWV_FLOW_STRING.JOIN' must be declared ORA-06550: line 168, column 1: PL/SQL: Statement ignored

Worth a try. Must be something in the export that's incompatible with 5.0.

Oh well.

**Comment by RonnyWeiss** [comment]
Hello

Yes this plug-in is not backward compatible to 5.0 have you try it in newer APEX because in 5.1.3.+ it’s working!

Kind regards

Ronny

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Steve Miles <notifications@github.com>
Gesendet: Wednesday, April 10, 2019 1:00:12 PM
An: RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex
Cc: Ronny Weiss; Comment
Betreff: Re: [RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex] Apex 5.0.1.00.06 (#1)


Execution of the statement was unsuccessful. ORA-06550: line 8, column 16: PLS-00201: identifier 'WWV_FLOW_STRING.JOIN' must be declared ORA-06550: line 2, column 1: PL/SQL: Statement ignored ORA-06550: line 145, column 19: PLS-00201: identifier 'WWV_FLOW_STRING.JOIN' must be declared ORA-06550: line 136, column 1: PL/SQL: Statement ignored ORA-06550: line 172, column 19: PLS-00201: identifier 'WWV_FLOW_STRING.JOIN' must be declared ORA-06550: line 168, column 1: PL/SQL: Statement ignored

Worth a try. Must be something in the export that's incompatible with 5.0.

Oh well.

**Comment by SmileyMan** [comment]
Stuck on 5.0 and Oracle 12.1 (No JSON)..

Big company so will not upgrade to satisfy one person :(

**Comment by RonnyWeiss** [comment]
Hello

The onlx Chance is to copy the plug-in manually to APEX 5.0 (PL/SQL Block, Static Files…) That is not very difficult so Maybe you could try that?!

LG Ronny

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Steve Miles <notifications@github.com>
Gesendet: Wednesday, April 10, 2019 1:08:58 PM
An: RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex
Cc: Ronny Weiss; Comment
Betreff: Re: [RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex] Apex 5.0.1.00.06 (#1)


Stuck on 5.0 and Oracle 12.1 (No JSON)..

Big company so will not upgrade to satisfy one person :(

**Comment by SmileyMan** [comment]
Hi.

Was my next plan. Hey Presto:

[APEX 5.0 Version](https://github.com/SmileyMan/APEX5.0-Material-Dashboard-Cards)

Thanks. All linked back to yourself.
